name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements_dev.txt

      - name: Executar lint
        run: task lint

      - name: Executar testes
        env:
          SECRET_KEY: your_secret_key
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
        run: task test
